# Generated by Django 6.0 on 2025-12-25 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.IntegerField(max_length=50, primary_key=True, serialize=False)),
                ('category_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('time', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('send_by', models.EmailField(max_length=50)),
                ('send_to', models.EmailField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('email_id', models.CharField(max_length=100)),
                ('phn_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('usertype', models.CharField(default='user', max_length=20)),
            ],
            options={
                'db_table': 'user_registration',
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('Reminder_desc', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.IntegerField(max_length=20, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('amount', models.FloatField(max_length=100)),
                ('Transaction_desc', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='user.category')),
            ],
        ),
    ]
