# Generated by Django 5.2.11 on 2026-02-09 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('send_by', models.EmailField(max_length=50)),
                ('send_to', models.EmailField(max_length=50)),
                ('Description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('confirm_password', models.CharField(max_length=100)),
                ('email_id', models.EmailField(max_length=254)),
                ('phn_no', models.CharField(max_length=15)),
                ('location', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('user', 'User'), ('family', 'Family Member')], max_length=10)),
                ('otp', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=50)),
                ('Reminder_desc', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=100)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reminder', to='user.registration')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('amount', models.FloatField()),
                ('Transaction_desc', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transaction', to='user.registration')),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.category')),
            ],
        ),
    ]
