# Generated by Django 6.0 on 2025-12-28 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='usertype',
        ),
        migrations.AddField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('family', 'Family Member')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='registration',
            name='username',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterModelTable(
            name='registration',
            table=None,
        ),
    ]
