# Generated by Django 5.2.8 on 2025-11-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='confirm_password',
            field=models.CharField(default=' ', max_length=100),
        ),
    ]
