# Generated by Django 6.0 on 2025-12-28 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_registration_usertype_registration_role_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('family', 'Family Member')], max_length=10),
        ),
    ]
