# Generated by Django 6.0.2 on 2026-02-17 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registration_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='confirm_password',
        ),
    ]
