# Generated by Django 5.2.8 on 2025-12-05 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_registration_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Registration_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spend_by', to='user.registration'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Categories', to='user.category'),
        ),
    ]
