# Generated by Django 6.0 on 2026-01-02 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_transaction_owner_type_alter_transaction_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
