# Generated by Django 6.0 on 2026-01-03 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_registration_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='reminder',
            name='owner_type',
            field=models.CharField(choices=[('user', 'User'), ('family', 'Family')], default='user', max_length=10),
            preserve_default=False,
        ),
    ]
