# Generated by Django 6.0.2 on 2026-02-17 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_registration_confirm_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
