# Generated by Django 6.0.2 on 2026-02-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_registration_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
